import { ScrollView, Text, StyleSheet, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { colors, type, space } from "@/src/theme";
import { IAP_ENABLED } from "@/src/lib/featureFlags";

export default function Terms() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.root} edges={["top", "left", "right"]}>
      <View style={styles.topBar}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={[type.overline, { color: colors.text }]}>Terms of Use</Text>
        <View style={{ width: 24 }} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.updated}>Last updated: June 2026</Text>

        <Text style={styles.h2}>1. Acceptance of Terms</Text>
        <Text style={styles.body}>
          By downloading, installing, or using the Wardrobe app, you agree to be bound by these Terms of Use. If you do not agree, do not use the app.
        </Text>

        <Text style={styles.h2}>2. Description of Service</Text>
        <Text style={styles.body}>
          Wardrobe is a digital wardrobe management application that uses AI to catalog your clothing, suggest outfits, and help you organise your wardrobe. The service is provided "as is" and is subject to change.
        </Text>

        <Text style={styles.h2}>3. User Accounts</Text>
        <Text style={styles.body}>
          You are responsible for maintaining the confidentiality of your account credentials. You must be at least 13 years of age to create an account. You agree to provide accurate and current information when creating your account.
        </Text>

        <Text style={styles.h2}>4. Acceptable Use</Text>
        <Text style={styles.body}>
          You agree not to:{"\n"}
          • Upload content that is illegal, harmful, or violates the rights of others{"\n"}
          • Attempt to reverse-engineer, hack, or disrupt the service{"\n"}
          • Use the service for commercial purposes without written permission{"\n"}
          • Upload images of other people without their consent
        </Text>

        <Text style={styles.h2}>5. Content Ownership</Text>
        <Text style={styles.body}>
          You retain ownership of the photos and content you upload. By uploading content, you grant Wardrobe a limited licence to store and process that content solely for the purpose of providing the service to you.
        </Text>

        <Text style={styles.h2}>6. AI-Generated Content</Text>
        <Text style={styles.body}>
          Outfit suggestions, clothing tags, and style advice are generated by AI and are provided for informational and entertainment purposes only. We make no warranties regarding the accuracy, completeness, or suitability of AI-generated content.
        </Text>

        {IAP_ENABLED ? (
          <>
            <Text style={styles.h2}>7. Subscriptions and Payments</Text>
            <Text style={styles.body}>
              Paid plans are billed through Square. By subscribing, you authorise recurring charges. You may cancel at any time; cancellations take effect at the end of the current billing period. Refunds are handled in accordance with applicable law.
            </Text>
          </>
        ) : (
          <>
            <Text style={styles.h2}>7. Pricing</Text>
            <Text style={styles.body}>
              Wardrobe is currently free to use. If paid features are introduced in the future, these terms will be updated and you will be notified before any charge applies.
            </Text>
          </>
        )}

        <Text style={styles.h2}>8. Disclaimers</Text>
        <Text style={styles.body}>
          Wardrobe is provided "as is" without warranties of any kind, express or implied. We do not guarantee uninterrupted access to the service. We are not responsible for any loss of data.
        </Text>

        <Text style={styles.h2}>9. Limitation of Liability</Text>
        <Text style={styles.body}>
          To the fullest extent permitted by law, Wardrobe shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
        </Text>

        <Text style={styles.h2}>10. Changes to Terms</Text>
        <Text style={styles.body}>
          We may update these terms at any time. Continued use of the app after changes constitutes acceptance of the revised terms. We will notify users of material changes via email or in-app notice.
        </Text>

        <Text style={styles.h2}>11. Governing Law</Text>
        <Text style={styles.body}>
          These terms are governed by the laws of the State of Florida, United States, without regard to conflict of law principles.
        </Text>

        <Text style={styles.h2}>12. Contact</Text>
        <Text style={styles.body}>
          For questions about these terms, contact us at:{"\n"}
          legal@Wardrobe.app
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: space.lg,
    paddingVertical: space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  content: { padding: space.lg, paddingBottom: 60 },
  updated: { color: colors.textSecondary, fontSize: 12, marginBottom: space.xl },
  h2: { color: colors.text, fontSize: 15, fontWeight: "700", marginTop: space.xl, marginBottom: space.sm },
  body: { color: colors.textSecondary, fontSize: 14, lineHeight: 22 },
});
